SWIDEA_SITE/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

SWIDEA_SITE/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ideas/', include('ideas.urls')),
    path('devtools/', include('devtools.urls')),
    path('accounts/', include('accounts.urls')), # 추가
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SWIDEA_SITE/ideas/urls.py
from django.urls import path
from . import views

app_name = 'ideas'

urlpatterns = [
    path('', views.idea_list, name='idea_list'),
    
    path('create/', views.idea_create, name='idea_create'),

    path('<int:pk>/', views.idea_detail, name='idea_detail'),

    path('<int:pk>/update/', views.idea_update, name='idea_update'),

    path('<int:pk>/delete/', views.idea_delete, name='idea_delete'),
    
    path('<int:pk>/toggle_star/', views.toggle_star, name='toggle_star'),
    path('<int:pk>/adjust_interest/', views.adjust_interest, name='adjust_interest'),
]

SWIDEA_SITE/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}SW IDEA{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
  
  <header class="main-header">
      <div class="container">
          <div class="logo">
              <a href="{% url 'ideas:idea_list' %}">SWIDEA</a>
          </div>
          <nav>
              {% if user.is_authenticated %}
                  <span>환영합니다, <strong>{{ user.username }}</strong>님!</span>
                  <a href="{% url 'accounts:logout' %}">로그아웃</a>
              {% else %}
                  <a href="{% url 'accounts:login' %}">로그인</a>
                  <a href="{% url 'accounts:signup' %}">회원가입</a>
              {% endif %}
          </nav>
      </div>
  </header>

  <main class="container">
      {% block content %}
      {% endblock %}
  </main>
</body>
</html>